title:            Fatih Hayrioğlu'nun not defteri
description:      "{ CSS, HTML ve Javascript }"
disqus_shortname: fatihhayri
reading_time:     true
words_per_minute: 200
lang: 'tr_TR'
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://localhost:4000

# Owner/author information
owner:
  name:           Fatih Hayrioğlu
  avatar:         avatar.jpg
  bio:            "Arayüz Geliştirici Gudi"
  email:          fatih.hayrioglu@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: fatihhayri
  facebook:
  github: fatihhayri
  stackexchange:
  linkedin: fatihhayri
  instagram:
  flickr:
  tumblr: fatihhayri
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Hakkımda
    url: /hakkimda
  - title: CSS Dersleri
    url: /css-dersleri
  - title: Git
    url: /git
  - title: Kitap
    url: /kitap
  - title: Sass
    url: /sass
  - title: İletişim
    url: /iletisim

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Istanbul
future:      true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 3
paginate_path: "page:num"

kramdown:
  input: GFM

coderay:
  coderay_line_numbers: nil
  coderay_line_numbers_start: 1
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
excerpt_separator: ""